import Config from "../config"

export const API_BASE_URL = Config.API_BASE_URL;
export const API_ASSETS_URL = Config.API_ASSETS_URL;

export const AWS_REGION_NAME = Config.AWS_REGION_NAME;
export const AWS_ACCESS_KEY_ID = Config.AWS_ACCESS_KEY_ID;
export const AWS_SECRET_ACCESS_KEY = Config.AWS_SECRET_ACCESS_KEY;

export const COUNTRIES_PHONE_CODE = [
    { "label": "+1", "value": "+1" },
    { "label": "+44", "value": "+44" },
   ]
// export const COUNTRIES_PHONE_CODE = [
//     { "label": "+92", "value": "+92" },
//     { "label": "+93", "value": "+93" },
//     { "label": "+358", "value": "+358" },
//     { "label": "+355", "value": "+355" },
//     { "label": "+213", "value": "+213" },
//     { "label": "+376", "value": "+376" },
//     { "label": "+244", "value": "+244" },
//     { "label": "+672", "value": "+672" },
//     { "label": "+54", "value": "+54" },
//     { "label": "+374", "value": "+374" },
//     { "label": "+297", "value": "+297" },
//     { "label": "+61", "value": "+61" },
//     { "label": "+43", "value": "+43" },
//     { "label": "+994", "value": "+994" },
//     { "label": "+973", "value": "+973" },
//     { "label": "+880", "value": "+880" },
//     { "label": "+375", "value": "+375" },
//     { "label": "+32", "value": "+32" },
//     { "label": "+501", "value": "+501" },
//     { "label": "+229", "value": "+229" },
//     { "label": "+975", "value": "+975" },
//     { "label": "+591", "value": "+591" },
//     { "label": "+387", "value": "+387" },
//     { "label": "+267", "value": "+267" },
//     { "label": "+55", "value": "+55" },
//     { "label": "+246", "value": "+246" },
//     { "label": "+673", "value": "+673" },
//     { "label": "+359", "value": "+359" },
//     { "label": "+226", "value": "+226" },
//     { "label": "+257", "value": "+257" },
//     { "label": "+855", "value": "+855" },
//     { "label": "+237", "value": "+237" },
//     { "label": "+238", "value": "+238" },
//     { "label": "+236", "value": "+236" },
//     { "label": "+235", "value": "+235" },
//     { "label": "+56", "value": "+56" },
//     { "label": "+86", "value": "+86" },
//     { "label": "+57", "value": "+57" },
//     { "label": "+269", "value": "+269" },
//     { "label": "+506", "value": "+506" },
//     { "label": "+385", "value": "+385" },
//     { "label": "+53", "value": "+53" },
//     { "label": "+357", "value": "+357" },
//     { "label": "+420", "value": "+420" },
//     { "label": "+45", "value": "+45" },
//     { "label": "+253", "value": "+253" },
//     { "label": "+593", "value": "+593" },
//     { "label": "+20", "value": "+20" },
//     { "label": "+503", "value": "+503" },
//     { "label": "+240", "value": "+240" },
//     { "label": "+291", "value": "+291" },
//     { "label": "+372", "value": "+372" },
//     { "label": "+251", "value": "+251" },
//     { "label": "+500", "value": "+500" },
//     { "label": "+298", "value": "+298" },
//     { "label": "+679", "value": "+679" },
//     { "label": "+358", "value": "+358" },
//     { "label": "+33", "value": "+33" },
//     { "label": "+689", "value": "+689" },
//     { "label": "+241", "value": "+241" },
//     { "label": "+220", "value": "+220" },
//     { "label": "+995", "value": "+995" },
//     { "label": "+49", "value": "+49" },
//     { "label": "+233", "value": "+233" },
//     { "label": "+350", "value": "+350" },
//     { "label": "+30", "value": "+30" },
//     { "label": "+299", "value": "+299" },
//     { "label": "+502", "value": "+602" },
//     { "label": "+224", "value": "+224" },
//     { "label": "+245", "value": "+245" },
//     { "label": "+592", "value": "+592" },
//     { "label": "+509", "value": "+509" },
//     { "label": "+504", "value": "+504" },
//     { "label": "+852", "value": "+852" },
//     { "label": "+36", "value": "+36" },
//     { "label": "+354", "value": "+354" },
//     { "label": "+91", "value": "+91" },
//     { "label": "+62", "value": "+62" },
//     { "label": "+98", "value": "+98" },
//     { "label": "+964", "value": "+964" },
//     { "label": "+353", "value": "+353" },
//     { "label": "+972", "value": "+972" },
//     { "label": "+39", "value": "+39" },
//     { "label": "+225", "value": "+225" },
//     { "label": "+81", "value": "+81" },
//     { "label": "+962", "value": "+962" },
//     { "label": "+7", "value": "+7" },
//     { "label": "+254", "value": "+254" },
//     { "label": "+686", "value": "+686" },
//     { "label": "+850", "value": "+850" },
//     { "label": "+82", "value": "+82" },
//     { "label": "+965", "value": "+965" },
//     { "label": "+996", "value": "+996" },
//     { "label": "+856", "value": "+856" },
//     { "label": "+371", "value": "+371" },
//     { "label": "+961", "value": "+961" },
//     { "label": "+266", "value": "+266" },
//     { "label": "+231", "value": "+231" },
//     { "label": "+218", "value": "+218" },
//     { "label": "+423", "value": "+423" },]


export const COUNTRIES_CURRENCY_CODE = [
    { "label": "CAD", "value": "CAD" },
    { "label": "USD", "value": "USD" },
    { "label": "EUR", "value": "EUR" },
    { "label": "GBP", "value": "GBP" },
    { "label": "JPY", "value": "JPY" },
    { "label": "AUD", "value": "AUD" },
    { "label": "CHF", "value": "CHF" },
    { "label": "CNY", "value": "CNY" },
    { "label": "KRW", "value": "KRW" },
    { "label": "BRL", "value": "BRL" },
    { "label": "INR", "value": "INR" },
    { "label": "RUB", "value": "RUB" },
    { "label": "MXN", "value": "MXN" },
    { "label": "ZAR", "value": "ZAR" },
    { "label": "SAR", "value": "SAR" },
    { "label": "TRY", "value": "TRY" },
    { "label": "SGD", "value": "SGD" },
    { "label": "SEK", "value": "SEK" },
    { "label": "NZD", "value": "NZD" },
    { "label": "NOK", "value": "NOK" },
    { "label": "HKD", "value": "HKD" },
    { "label": "PLN", "value": "PLN" },
    { "label": "DKK", "value": "DKK" },
    { "label": "MYR", "value": "MYR" },
    { "label": "IDR", "value": "IDR" },
    { "label": "THB", "value": "THB" },
    { "label": "PHP", "value": "PHP" },
    { "label": "EGP", "value": "EGP" },
    { "label": "COP", "value": "COP" },
    { "label": "CLP", "value": "CLP" },
    { "label": "ARS", "value": "ARS" },
    { "label": "NGN", "value": "NGN" },
    { "label": "PKR", "value": "PKR" },
    { "label": "VND", "value": "VND" },
    { "label": "UAH", "value": "UAH" },
    { "label": "RON", "value": "RON" },
    { "label": "PEN", "value": "PEN" },
    { "label": "CZK", "value": "CZK" },
    { "label": "ILS", "value": "ILS" },
    { "label": "BDT", "value": "BDT" },
    { "label": "HUF", "value": "HUF" },
    { "label": "KZT", "value": "KZT" },
    { "label": "IQD", "value": "IQD" },
    { "label": "VES", "value": "VES" },
    { "label": "LBP", "value": "LBP" },
    { "label": "MAD", "value": "MAD" },
    { "label": "VES", "value": "VES" },
    { "label": "BYN", "value": "BYN" },
];
export const RANDOM_CATEGORIES = [
    { "label": "Groceries", "value": "Groceries" },
    { "label": "Electronics", "value": "Electronics" },
    { "label": "Clothing", "value": "Clothing" },
    { "label": "Entertainment", "value": "Entertainment" },
    { "label": "Home Decor", "value": "Home Decor" },
    { "label": "Fitness", "value": "Fitness" },
    { "label": "Travel", "value": "Travel" },
    { "label": "Healthcare", "value": "Healthcare" },
    { "label": "Books", "value": "Books" },
    { "label": "Gifts", "value": "Gifts" },
] as any; 

export const RANDOM_METHODS_OF_PAYMENT = [
    { "label": "Credit Card", "value": "credit_card" },
    { "label": "Debit Card", "value": "debit_card" },
    { "label": "Cash", "value": "cash" },
    { "label": "Mobile Payment", "value": "mobile_payment" },
    { "label": "Online Payment", "value": "online_payment" },
    { "label": "Bank Transfer", "value": "bank_transfer" },
    { "label": "PayPal", "value": "paypal" },
    { "label": "Cryptocurrency", "value": "cryptocurrency" },
    { "label": "Gift Card", "value": "gift_card" },
    { "label": "Check", "value": "check" }
];
